### ISSUE TITLE
Introduce spec.halted and removed dormant and snapshot cr

### ISSUE THREAD

**Issue by the-redback** [kubedb/issues#709]
- [ ] Apimachinery: https://github.com/kubedb/apimachinery/pull/486
- [ ] Installer: https://github.com/kubedb/installer/pull/44
- [ ] MongoDB: https://github.com/kubedb/mongodb/pull/183
- [ ] Postgres
- [ ] MySQL
- [ ] Elasticsearch
- [ ] Memcached
- [ ] Redis
